name: release-mac

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: cd packages/app && yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}


