name: test-mac

on: 
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/player/**'

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: cd packages/player && yarn build:test
      - run: cd packages/player && yarn test
        env:
          DEBUG: "pw:browser*"


